[ClassVersion("1.0.1.0"), FriendlyName("xComputer")]
class MSFT_xComputer : OMI_BaseResource
{
    [Key, Description("The computer name to set")] string Name;
    [Write, Description("The domain to join to")] string DomainName;
    [Write, Description("The organizational unit to join to")] string JoinOU;
    [Read, Description("The current machine organizational unit")] string CurrentOU;
    [Write,EmbeddedInstance("MSFT_Credential"), Description("The credential used to join to a domain")] String Credential;
    [Write,EmbeddedInstance("MSFT_Credential"), Description("The credential used to unjoin a domain")] String UnjoinCredential;
    [Write, Description("The local work group name")] string WorkGroupName;
    [Write, Description("The computer description that will be set in Active Directory and locally")] String Description;
};
